#!/bin/bash

# This script is designed to cycle through all of your vNodes and move all of your PRV to one main account
# It will leave a reserve amount in each account
# Enter your own private keys and destination address
# Use at your own risk

declare int R = 10000000 # reserve amount to be left in each account to fund future transactions (like sending tokens)

# declare ADDR = youDestinationAddressHere # enter Incognito address to send all funds to 

# private key array

# for keys in array
# check wallet balance
# if balance greater than R
#     move to ADDR 
# else move on to next key

echo -e "Done!"
